//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblCurrencyCodesM
    {
        public int iCurrencyId { get; set; }
        public string sCurrencyCode { get; set; }
        public string sCurrencyName { get; set; }
    }
}
