//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblCodeM
    {
        public int iCodeId { get; set; }
        public Nullable<int> iCodeTypeId { get; set; }
        public string sCode { get; set; }
        public string sCodeName { get; set; }
        public string sCodeDescription { get; set; }
    
        public virtual tblCodeTypeM tblCodeTypeM { get; set; }
    }
}
