//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblHouseCargoDescriptionMasterConsignmentMap
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblHouseCargoDescriptionMasterConsignmentMap()
        {
            this.tblAdditionalDetailsHouseCargoMaps = new HashSet<tblAdditionalDetailsHouseCargoMap>();
            this.tblItemDetailsHouseCargoMaps = new HashSet<tblItemDetailsHouseCargoMap>();
            this.tblItineraryHouseCargoMaps = new HashSet<tblItineraryHouseCargoMap>();
            this.tblSupportDocHouseCargoMaps = new HashSet<tblSupportDocHouseCargoMap>();
            this.tblTransportEquipmentHouseCargoMaps = new HashSet<tblTransportEquipmentHouseCargoMap>();
        }
    
        public int iHouseCargoDescId { get; set; }
        public int iMasterConsignmentId { get; set; }
        public Nullable<int> iMessageImplementationId { get; set; }
        public Nullable<decimal> dHCRefSubLineNo { get; set; }
        public string sHCRefBillNo { get; set; }
        public Nullable<System.DateTime> dtHCRefBillDate { get; set; }
        public string sHCRefConsolidatedIndicator { get; set; }
        public string sHCRefConsolidatorPan { get; set; }
        public string sHCRefPreviousDescription { get; set; }
        public string sLocCstmFirstPartyOfEntry { get; set; }
        public string sLocCstmDestinationPort { get; set; }
        public string sLocCstmNextPortOfUnlading { get; set; }
        public string sLocCstmTypeOfCargo { get; set; }
        public string sLocCstmItemType { get; set; }
        public string sLocCstmCargoMovement { get; set; }
        public string sLocCstmNatureOfCargo { get; set; }
        public string sLocCstmSplitIndicator { get; set; }
        public Nullable<decimal> dNoOfPackages { get; set; }
        public string sLocCstmTypeOfPakages { get; set; }
        public string sTrnshprTranshipperCd { get; set; }
        public string sTrnshprTranshipperBond { get; set; }
        public string sTrnsprtrDocPartyPortOfAcceptedCCd { get; set; }
        public string sTrnsprtrDocPartyPortOfAcceptedName { get; set; }
        public string sTrnsprtrDocPartyPortOfReceiptCcd { get; set; }
        public string sTrnsprtrDocPartyPortOfReceiptName { get; set; }
        public string sTrnsprtrDocPartyConsignorName { get; set; }
        public string sTrnsprtrDocPartyConsignorCd { get; set; }
        public string sTrnsprtrDocPartyConsignorCdType { get; set; }
        public string sTrnsprtrDocPartyConsignorStreetAddress { get; set; }
        public string sTrnsprtrDocPartyConsignorCity { get; set; }
        public string sTrnsprtrDocPartyConsignorCountrySubDivName { get; set; }
        public string sTrnsprtrDocPartyConsignorCountrySubDivCd { get; set; }
        public string sTrnsprtrDocPartyConsignorCountryCd { get; set; }
        public string sTrnsprtrDocPartyConsignorPostCd { get; set; }
        public string sTrnsprtrDocPartyConsigneeName { get; set; }
        public string sTrnsprtrDocPartyConsigneeCd { get; set; }
        public string sTrnsprtrDocPartyTypeOfCd { get; set; }
        public string sTrnsprtrDocPartyConsigneeStreetAddress { get; set; }
        public string sTrnsprtrDocPartyConsigneeCity { get; set; }
        public string sTrnsprtrDocPartyConsigneeCountrySubDivName { get; set; }
        public string sTrnsprtrDocPartyConsigneeCountrySubDiv { get; set; }
        public string sTrnsprtrDocPartyConsigneeCountryCd { get; set; }
        public string sTrnsprtrDocPartyConsigneePostCd { get; set; }
        public string sTrnsprtrDocPartyNameOfAnyOtherNotFdParty { get; set; }
        public string sTrnsprtrDocPartyPANOfNotFdParty { get; set; }
        public string sTrnsprtrDocPartyTypeOfNotFdPartyCd { get; set; }
        public string sTrnsprtrDocPartyNotFdPartyStreetAddress { get; set; }
        public string sTrnsprtrDocPartyNotFdPartyCity { get; set; }
        public string sTrnsprtrDocPartyNotFdPartyCountrySubDivName { get; set; }
        public string sTrnsprtrDocPartyNotFdPartyCountrySubDiv { get; set; }
        public string sTrnsprtrDocPartyNotFdPartyCountryCd { get; set; }
        public string sTrnsprtrDocPartyNotFdPartyPostCd { get; set; }
        public string sTrnsprtrDocPartyGoodsDescAsPerBill { get; set; }
        public string sTrnsprtrDocPartyUCRType { get; set; }
        public string sTrnsprtrDocPartyUCRCd { get; set; }
        public Nullable<decimal> dTrnsprtrDocMsrNoOfPackages { get; set; }
        public string sTrnsprtrDocMsrTypesOfPackages { get; set; }
        public string sTrnsprtrDocMsrMarksNoOnPackages { get; set; }
        public Nullable<decimal> dTrnsprtrDocMsrGrossWeight { get; set; }
        public Nullable<decimal> dTrnsprtrDocMsrNetWeight { get; set; }
        public string sTrnsprtrDocMsrUnitOfWeight { get; set; }
        public Nullable<decimal> dTrnsprtrDocMsrGrossVolume { get; set; }
        public string sTrnsprtrDocMsrUnitOfVolume { get; set; }
        public Nullable<decimal> dTrnsprtrDocMsrInvoiceValueOfConsigment { get; set; }
        public string sTrnsprtrDocMsrCurrencyCd { get; set; }
        public Nullable<System.DateTime> dtActionDate { get; set; }
        public Nullable<int> iActionBy { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblAdditionalDetailsHouseCargoMap> tblAdditionalDetailsHouseCargoMaps { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblItemDetailsHouseCargoMap> tblItemDetailsHouseCargoMaps { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblItineraryHouseCargoMap> tblItineraryHouseCargoMaps { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblSupportDocHouseCargoMap> tblSupportDocHouseCargoMaps { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblTransportEquipmentHouseCargoMap> tblTransportEquipmentHouseCargoMaps { get; set; }
        public virtual tblMasterConsignmentMessageImplementationMap tblMasterConsignmentMessageImplementationMap { get; set; }
        public virtual tblMessageImplementation tblMessageImplementation { get; set; }
    }
}
