//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblItemDetailsHouseCargoMap
    {
        public int iItemsDetailsId { get; set; }
        public Nullable<int> iMasterConsignmentId { get; set; }
        public Nullable<int> iHouseCargoDescId { get; set; }
        public Nullable<decimal> dCargoItemSequenceNo { get; set; }
        public string sHsCd { get; set; }
        public string sCargoItemDesc { get; set; }
        public string sUnoCd { get; set; }
        public string sIMDGCd { get; set; }
        public Nullable<decimal> dNoOfPakages { get; set; }
        public string sTypesOfPackages { get; set; }
        public Nullable<System.DateTime> dtActionDate { get; set; }
        public Nullable<int> iActionBy { get; set; }
    
        public virtual tblMasterConsignmentMessageImplementationMap tblMasterConsignmentMessageImplementationMap { get; set; }
        public virtual tblHouseCargoDescriptionMasterConsignmentMap tblHouseCargoDescriptionMasterConsignmentMap { get; set; }
    }
}
