//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblItineraryHouseCargoMap
    {
        public int iItineraryId { get; set; }
        public Nullable<int> iMasterConsignmentId { get; set; }
        public Nullable<int> iHouseCargoDescId { get; set; }
        public Nullable<decimal> dPortOfCallSequenceNo { get; set; }
        public string sPortOfCallCd { get; set; }
        public string sPortOfCallName { get; set; }
        public string sNextPortOfCallCdd { get; set; }
        public string sNextPortOfCallName { get; set; }
        public string sModeOfTransport { get; set; }
        public Nullable<System.DateTime> dtActionDate { get; set; }
        public Nullable<int> iActionBy { get; set; }
    
        public virtual tblHouseCargoDescriptionMasterConsignmentMap tblHouseCargoDescriptionMasterConsignmentMap { get; set; }
        public virtual tblMasterConsignmentMessageImplementationMap tblMasterConsignmentMessageImplementationMap { get; set; }
    }
}
