//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblMessageImplementation
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblMessageImplementation()
        {
            this.tblAdditionalDetailsMasterConsignmentMaps = new HashSet<tblAdditionalDetailsMasterConsignmentMap>();
            this.tblAdditionalDetailsMasterConsignmentMaps1 = new HashSet<tblAdditionalDetailsMasterConsignmentMap>();
            this.tblAmendmentDetailsMessageImlementationMaps = new HashSet<tblAmendmentDetailsMessageImlementationMap>();
            this.tblItemDetailsMasterConsignmentMaps = new HashSet<tblItemDetailsMasterConsignmentMap>();
            this.tblItineraryMasterConsignmentMaps = new HashSet<tblItineraryMasterConsignmentMap>();
            this.tblPersonOnBoardMessageImlementationMaps = new HashSet<tblPersonOnBoardMessageImlementationMap>();
            this.tblSupportDocMasterConsignmentMaps = new HashSet<tblSupportDocMasterConsignmentMap>();
            this.tblTmAdditionalDetailsMessageImplementationMaps = new HashSet<tblTmAdditionalDetailsMessageImplementationMap>();
            this.tblTmSupportDocMessageImplementationMaps = new HashSet<tblTmSupportDocMessageImplementationMap>();
            this.tblTransportEquipmentMasterConsignmentMaps = new HashSet<tblTransportEquipmentMasterConsignmentMap>();
            this.tblVoyageTransporterEquipmentMessageImlementationMaps = new HashSet<tblVoyageTransporterEquipmentMessageImlementationMap>();
            this.tblHouseCargoDescriptionMasterConsignmentMaps = new HashSet<tblHouseCargoDescriptionMasterConsignmentMap>();
            this.tblMasterConsignmentMessageImplementationMaps = new HashSet<tblMasterConsignmentMessageImplementationMap>();
        }
    
        public int iMessageImplementationId { get; set; }
        public string sHeaderFieldSenderId { get; set; }
        public string sHeaderFieldReceiverId { get; set; }
        public string sHeaderFieldVersionNo { get; set; }
        public string sHeaderFieldIndicator { get; set; }
        public string sHeaderFieldMessageId { get; set; }
        public Nullable<decimal> dHeaderFieldSequenceOrControlNumber { get; set; }
        public Nullable<System.DateTime> dtHeaderFieldDateTime { get; set; }
        public string sHeaderFieldReportingEvent { get; set; }
        public string sDecRefMsgType { get; set; }
        public string sDecRefPortOfReporting { get; set; }
        public Nullable<decimal> dDecRefjobNo { get; set; }
        public Nullable<System.DateTime> dtDecRefJobDt { get; set; }
        public string sDecRefReportingEvent { get; set; }
        public Nullable<decimal> dDecRefManifestNoRotnNo { get; set; }
        public Nullable<System.DateTime> dtDecRefManifestDateRotnDt { get; set; }
        public string sDecRefVesselTypeMovement { get; set; }
        public Nullable<decimal> dDecRefDptrPreviousManifestNo { get; set; }
        public Nullable<System.DateTime> dtDecRefPreviousManifestDptrDate { get; set; }
        public string sAuthPrsnSubmitType { get; set; }
        public string sAuthPrsnSubmitCode { get; set; }
        public string sAuthPrsnAuthRepresentativePAN { get; set; }
        public string sAuthPrsnShipLineCode { get; set; }
        public string sAuthPrsnAuthSeaCarrierCode { get; set; }
        public string sAuthPrsnMasterName { get; set; }
        public string sAuthPrsnShippingLineBondNo { get; set; }
        public string sAuthPrsnTerminalCustodianCode { get; set; }
        public string sVesselDtlsModeOfTransport { get; set; }
        public string sVesselDtlsTypeOfTransportMeans { get; set; }
        public string sVesselDtlsTransportMeansId { get; set; }
        public string sVesselDtlsShipType { get; set; }
        public string sVesselDtlsPurposeOfCall { get; set; }
        public string sVoyageDtlsVoyageNo { get; set; }
        public string sVoyageDtlsConveinceRefNo { get; set; }
        public string sVoyageDtlsTotalNumberofTrnsptEqtMnfstd { get; set; }
        public string sVoyageDtlsCargoDesCdd { get; set; }
        public string sVoyageDtlsBriefCargoDesc { get; set; }
        public Nullable<decimal> dVoyageDtlsTotalNumberOfLines { get; set; }
        public Nullable<System.DateTime> dtVoyageDtlsExpectedDtandTimeOfArrival { get; set; }
        public Nullable<System.DateTime> dtVoyageDtlsExpectedDtandTimeOfDeparture { get; set; }
        public Nullable<int> iVoyageDtlsNumberOfPsngrManifested { get; set; }
        public Nullable<int> iVoyageDtlsNumberOfCrewManifested { get; set; }
        public Nullable<int> iArvlDtlsNumberOfPassengers { get; set; }
        public Nullable<int> iArvlDtlsNumberOfCrew { get; set; }
        public Nullable<int> iArvlDtlsTotalNoOfCntrsLanded { get; set; }
        public Nullable<int> iArvlDtlsTotalOfCntrsLoaded { get; set; }
        public Nullable<int> iArvlDtlsTotalNoOfPersonOnBoard { get; set; }
        public Nullable<int> iArvlDtlsTotalNoOfTrnsprtEqReprtdOnArrDptr { get; set; }
        public Nullable<int> iArvlDtlsTotalNoOfTrnsprtCntrctReprtdOnArrDptr { get; set; }
        public string sDigiSignStartSignature { get; set; }
        public string sDigiSignStartCertificate { get; set; }
        public string sDigiSignSignerVersion { get; set; }
        public Nullable<System.DateTime> dtActionDate { get; set; }
        public Nullable<int> iActionBy { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblAdditionalDetailsMasterConsignmentMap> tblAdditionalDetailsMasterConsignmentMaps { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblAdditionalDetailsMasterConsignmentMap> tblAdditionalDetailsMasterConsignmentMaps1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblAmendmentDetailsMessageImlementationMap> tblAmendmentDetailsMessageImlementationMaps { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblItemDetailsMasterConsignmentMap> tblItemDetailsMasterConsignmentMaps { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblItineraryMasterConsignmentMap> tblItineraryMasterConsignmentMaps { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblPersonOnBoardMessageImlementationMap> tblPersonOnBoardMessageImlementationMaps { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblSupportDocMasterConsignmentMap> tblSupportDocMasterConsignmentMaps { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblTmAdditionalDetailsMessageImplementationMap> tblTmAdditionalDetailsMessageImplementationMaps { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblTmSupportDocMessageImplementationMap> tblTmSupportDocMessageImplementationMaps { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblTransportEquipmentMasterConsignmentMap> tblTransportEquipmentMasterConsignmentMaps { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblVoyageTransporterEquipmentMessageImlementationMap> tblVoyageTransporterEquipmentMessageImlementationMaps { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblHouseCargoDescriptionMasterConsignmentMap> tblHouseCargoDescriptionMasterConsignmentMaps { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblMasterConsignmentMessageImplementationMap> tblMasterConsignmentMessageImplementationMaps { get; set; }
    }
}
