//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblPortM
    {
        public int iPortId { get; set; }
        public string sPortCode { get; set; }
        public string sPortDescription { get; set; }
        public string sCountryCode { get; set; }
        public string SstateCode { get; set; }
    }
}
