//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblPersonOnBoardMessageImplementationMap
    {
        public int iPersonOnBoardId { get; set; }
        public Nullable<int> iMessageImplementationId { get; set; }
        public Nullable<decimal> dPersonOnBaordSeqNo { get; set; }
        public string sPersonDetailsPersonTypeCdd { get; set; }
        public string sPersonDetailsPersonFamilyName { get; set; }
        public string sPersonDetailsPersonGivenName { get; set; }
        public string sPersonDetailsPersonNationalityCdd { get; set; }
        public Nullable<decimal> dPersonDetailsPassengersInTransitIndicator { get; set; }
        public string sPersonDetailsCrewMemberRankOrRatingName { get; set; }
        public string sPersonDetailsCrewMemberRankOrRatingCdd { get; set; }
        public string sPersonDetailsPassangerPartOfEmbarkTnCdd { get; set; }
        public string sPersonDetailsPassangerPartOfEmbarkTnName { get; set; }
        public string sPersonDetailsPassangerPartOfDsmbarkTnCdd { get; set; }
        public string sPersonDetailsPassangerPartOfDsmbarkTnName { get; set; }
        public string sPersonDetailsPersonGenderCdd { get; set; }
        public Nullable<System.DateTime> dtPersonDetailsPersonDateOfBirth { get; set; }
        public string sPersonDetailsPersonPlaceOfBirthName { get; set; }
        public string sPersonDetailsPersonCountryOfBirthCdd { get; set; }
        public Nullable<System.DateTime> dtPersonIdDocExpiryDate { get; set; }
        public string sPersonIdOrTravelDocIssuingNationCdd { get; set; }
        public string sPersonIdOrTravelDocNo { get; set; }
        public string sPersonIdOrTravelDocTypeCdd { get; set; }
        public string sVisaDetailsPersonVisa { get; set; }
        public string sVisaDetailsPNRNo { get; set; }
        public Nullable<System.DateTime> dtActionDate { get; set; }
        public Nullable<int> iActionBy { get; set; }
    
        public virtual tblMessageImplementation tblMessageImplementation { get; set; }
    }
}
