//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblPermissionM
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblPermissionM()
        {
            this.tblRolePermissionsMs = new HashSet<tblRolePermissionsM>();
        }
    
        public int iPermissionId { get; set; }
        public int iParentId { get; set; }
        public string sPermissionName { get; set; }
        public string sPath { get; set; }
        public Nullable<byte> iOrder { get; set; }
        public Nullable<bool> bIsVisible { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblRolePermissionsM> tblRolePermissionsMs { get; set; }
    }
}
