//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblRolePermissionsM
    {
        public int iRolePermissionId { get; set; }
        public int iPermissionId { get; set; }
        public byte iRoleId { get; set; }
    
        public virtual tblRoleM tblRoleM { get; set; }
        public virtual tblPermissionM tblPermissionM { get; set; }
    }
}
