//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblUserM
    {
        public int iUserId { get; set; }
        public string sUserName { get; set; }
        public string sFirstName { get; set; }
        public string sLastName { get; set; }
        public string sEmailId { get; set; }
        public string sPhoneNumber { get; set; }
        public byte iRoleId { get; set; }
        public string sPassword { get; set; }
    
        public virtual tblRoleM tblRoleM { get; set; }
    }
}
